/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package YouTube.Fallen.Kingdoms;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
